apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    # here with this line port wil not be opened, just for information
    demo: service
spec:
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: service
  ports:
    - protocol: TCP
      port: 80 #service-poart
      targetPort: 80 #container-port
